<?php
$sticker = [
    1 => [
        "nom" => "Metal",
        "description"=>"Pour les fans de Metal et de paillettes",
        "prix"=>"0,80€",
        "id"=>"ACDC",
        "lien"=>""],
    2 => [
        "nom" => "Feu Multicolore",
        "description"=>"A chacun sa voie. N'attendez pas de passer au rose pour adotper ce sticker !",
        "prix"=>"0,90€",
        "id"=>"FeuR",
        "lien"=>""],
    3 => [
        "nom"=> "Dynamite",
        "description"=>"Une explosion de pailettes dans votre quotidien !!!",
        "prix"=>"1,10€",
        "id"=>"Bombe",
        "lien"=>""],
    4 => [
        "nom" => "L.G.B.D",
        "description"=>"Parce que le genre n'est pas un choix",
        "prix"=>"0,7O€",
        "id"=>"De",
        "lien"=>""],
    5 => [
        "nom" => "Panser ses blessures",
        "description"=>"Quand la vie vous blesse, on vous soigne",
        "prix"=>"1,00€",
        "id"=>"Mirroire",
        "lien"=>""],
    6 => [
        "nom" => "LE Superglue",
        "description"=>"Marquez votre appartenance au meilleur des groupes",
        "prix"=>"0,50€",
        "id"=>"THELogo",
        "lien"=>""],
];
?>